name = "webpush"
version = "1.0.0"
target = "erlang"
description = "A Gleam library for web push notifications"
licences = ["Apache-2.0"]
repository = { type = "github", user = "imlargo", repo = "gleam-webpush" }
links = [{ title = "Website", href = "https://github.com/imlargo/gleam-webpush" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
jose = ">= 1.11.8 and < 1.11.10"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
jiffy = ">= 1.1.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[erlang]
extra_applications = ["crypto", "public_key", "jose"]
