name = "examples"
version = "1.0.0"
gleam = ">= 1.11.0"
target = "erlang"

description = "Runnable examples for the webpush library"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
webpush = { path = ".." }

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"
